apiVersion: batch/v1
kind: Job
metadata:
  name: reanalyze-all-blocks
spec:
  template:
    spec:
      containers:
        - name: reanalyze-all-blocks
          image: registry.digitalocean.com/ultrasoundmoney/gas-analysis
          command: ["node", "src/reanalyze_all_blocks.js"]
          envFrom:
            - configMapRef:
                name: gas-analysis-env
            - secretRef:
                name: pg-password-anton
            - secretRef:
                name: node-urls
          env:
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      restartPolicy: Never
  backoffLimit: 4
