apiVersion: batch/v1
kind: Job
metadata:
  name: reanalyze-all-blocks
spec:
  template:
    spec:
      containers:
        - name: reanalyze-all-blocks
          image: registry.digitalocean.com/ultrasoundmoney/gas-analysis
          command: ["node", "src/reanalyze_all_blocks.js"]
          envFrom:
            - configMapRef:
                name: gas-analysis-env
            - secretRef:
                name: pg-password-anton
            - secretRef:
                name: node-urls
          env:
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GETH_URL
              value: ws://134.209.197.78:8546/
            - name: LOG_LEVEL
              value: info
            - name: ONLY_MISMATCH
              value: "true"
      restartPolicy: Never
  backoffLimit: 4
