version: "3.8"
services:
  postgresql:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=defaultdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
