import { Collection } from "../nft_go.js";

// 2022-03-22 11:10
export const rankedCollections: Collection[] = [
  {
    marketCap: 1659170490.292795,
    marketCapChange24h: 0.0002,
    name: "CryptoPunks",
    longDesc:
      "The CryptoPunks are 10,000 uniquely generated characters. No two are exactly alike, and each one of them can be officially owned by a single person on the Ethereum blockchain. Originally, they could be claimed for free by anybody with an Ethereum wallet, but all 10,000 were quickly claimed. Now they must be purchased from someone via the marketplace that's also embedded in the blockchain.",
    slug: "cryptopunks",
    link: "https://www.larvalabs.com/cryptopunks",
    logo: "https://static.nftgo.io/asset/1624854837360.png",
    blockchain: "ETH",
    contracts: ["0xb47e3cd837ddf8e4c57f05d70ab865de6e193bbb"],
    medias: {
      twitter: "https://www.twitter.com/larvalabs",
      discord: "https://discord.gg/tQp4pSE",
    },
  },
  {
    marketCap: 933742380.8226566,
    marketCapChange24h: 0.0029,
    name: "Bored Ape Yacht Club",
    longDesc:
      "The Bored Ape Yacht Club is a collection of 10,000 unique Bored Ape NFTs— unique digital collectibles living on the Ethereum blockchain. Your Bored Ape doubles as your Yacht Club membership card, and grants access to members-only benefits, the first of which is access to THE BATHROOM, a collaborative graffiti board. Future areas and perks can be unlocked by the community through roadmap activation.",
    slug: "bored-ape-yacht-club",
    link: "https://boredapeyachtclub.com/",
    logo: "https://lh3.googleusercontent.com/Ju9CkWtV-1Okvf45wo8UctR-M9He2PjILP0oOvxE89AyiPPGtrR3gysu1Zgy0hjd2xKIgjJJtWIc0ybj4Vd7wv8t3pxDGHoJBzDB=s130",
    blockchain: "ETH",
    contracts: ["0xbc4ca0eda7647a8ab7c2061c2e118a18a936f13d"],
    medias: {
      twitter: "https://twitter.com/boredapeyc",
      discord: "https://discord.com/invite/3P5K3dzgdB",
      telegram: null,
      instagram: "https://www.instagram.com/boredapeyachtclub/",
      medium: null,
    },
  },
  {
    marketCap: 836365110.4945757,
    marketCapChange24h: 0.0024,
    name: "Art Blocks",
    longDesc:
      "Art Blocks is a first of its kind platform focused on genuinely programmable on demand generative content that is stored immutably on the Ethereum Blockchain. You pick a style that you like, pay for the work, and a randomly generated version of the content is created by an algorithm and sent to your Ethereum account. The resulting piece might be a static image, 3D model, or an interactive experience. Each output is different and there are endless possibilities for the types of content that can be created on the platform.",
    slug: "art-blocks",
    link: "https://artblocks.io/",
    logo: "https://lh3.googleusercontent.com/GwnosrkaneKGEkWySxvTSzZ5bEUjWkRuQzLSNfrpgy2-gxYjoR3m5PohLT9Fzy0p1tohajZ1g-LFfF_ZLnS1GqlPNHPUaKUbDhbf=s130",
    blockchain: "ETH",
    contracts: [
      "0x059edd72cd353df5106d2b9cc5ab83a52287ac3a",
      "0xa7d8d9ef8d8ce8992df33d8b8cf4aebabd5bd270",
    ],
    medias: {
      twitter: "https://www.twitter.com/artblocks_io",
      discord: "https://discord.gg/artblocks",
      instagram: "https://www.instagram.com/artblocks_io",
    },
  },
  {
    marketCap: 738765666.4572625,
    marketCapChange24h: 0.0017,
    name: "Meebits",
    longDesc:
      "The Meebits are 20,000 unique 3D voxel characters, created by a custom generative algorithm, then registered on the Ethereum blockchain.",
    slug: "meebits",
    link: "https://meebits.larvalabs.com/",
    logo: "https://static.nftgo.io/asset/1624854698162.png",
    blockchain: "ETH",
    contracts: ["0x7bd29408f11d2bfc23c34f18275bbf23bb716bc7"],
    medias: { twitter: "https://twitter.com/larvalabs" },
  },
  {
    marketCap: 506297131.5459039,
    marketCapChange24h: 0.0025,
    name: "Mutant Ape Yacht Club",
    longDesc:
      "The MUTANT APE YACHT CLUB is a collection of up to 20,000 Mutant Apes that can only be created by exposing an existing Bored Ape to a vial of MUTANT SERUM or by minting a Mutant Ape in the public sale.",
    slug: "mutant-ape-yacht-club",
    link: "https://boredapeyachtclub.com/#/mayc",
    logo: "https://lh3.googleusercontent.com/lHexKRMpw-aoSyB1WdFBff5yfANLReFxHzt1DOj_sg7mS14yARpuvYcUtsyyx-Nkpk6WTcUPFoG53VnLJezYi8hAs0OxNZwlw6Y-dmI=s130",
    blockchain: "ETH",
    contracts: ["0x60e4d786628fea6478f785a6d7e704777c86a7c6"],
    medias: {
      twitter: "https://twitter.com/BoredApeYC",
      discord: "https://discord.gg/3P5K3dzgdB",
      youtube: "https://www.youtube.com/watch?v=xeDDq6BkScc",
      instagram: "https://www.instagram.com/boredapeyachtclub",
    },
  },
  {
    marketCap: 400673905.62225807,
    marketCapChange24h: 0,
    name: "Loot (for Adventurers)",
    longDesc:
      "Loot is randomized adventurer gear generated and stored on chain. Stats, images, and other functionality are intentionally omitted for others to interpret. Feel free to use Loot in any way you want.",
    slug: "loot-for-adventurers",
    link: "https://lootproject.com/",
    logo: "https://lh3.googleusercontent.com/g-NFUWjS4IGgym8PHBxyhg5-G_B4x-IHgPKRkxo00JQFE3LOd-95yU2uhrokITVmV7KHEav6OMfAhfJ4roC5hwP-0tI9dMRd9wQLdw=s130",
    blockchain: "ETH",
    contracts: ["0xff9c1b15b16263c61d017ee9f65c50e4ae0113d7"],
    medias: {
      twitter: "https://twitter.com/lootproject",
      discord: "https://discord.gg/Q5KGjftshm",
    },
  },
  {
    marketCap: 320890886.45445377,
    marketCapChange24h: 0.0013,
    name: "CLONE X - X TAKASHI MURAKAMI",
    longDesc:
      "🧬 CLONE X 🧬\n\n20,000 next-gen Avatars, by RTFKT and Takashi Murakami 🌸",
    slug: "rtfkt-clone-x-+-murakami",
    link: "https://www.rtfkt.com/",
    logo: "https://lh3.googleusercontent.com/XN0XuD8Uh3jyRWNtPTFeXJg_ht8m5ofDx6aHklOiy4amhFuWUa0JaR6It49AH8tlnYS386Q0TW_-Lmedn0UET_ko1a3CbJGeu5iHMg=s120",
    blockchain: "ETH",
    contracts: ["0x49cf6f5d44e70224e2e23fdcdd2c053f30ada28b"],
    medias: {
      twitter: "https://www.twitter.com/RTFKTstudios",
      instagram: "https://www.instagram.com/RTFKTSTUDIOS",
    },
  },
  {
    marketCap: 221329530.66060558,
    marketCapChange24h: 0.0024,
    name: "Azuki",
    longDesc:
      "A brand for the metaverse. Built by the community.\r\n\r\nAzuki starts with a collection of 10,000 avatars that give you membership access to The Garden: a corner of the internet where artists, builders, and web3 enthusiasts meet to create a decentralized future. Azuki holders receive access to exclusive drops, experiences, and more. Visit azuki.com for more details.\r\n\r\nWe rise together. We build together. We grow together.\r\n\r\nReady to take the red bean?",
    slug: "azuki",
    link: "http://www.azuki.com/",
    logo: "https://lh3.googleusercontent.com/H8jOCJuQokNqGBpkBN5wk1oZwO7LM8bNnrHCaekV2nKjnCqw6UB5oaH8XyNeBDj6bA_n1mjejzhFQUP3O1NfjFLHr3FOaeHcTOOT=s120",
    blockchain: "ETH",
    contracts: ["0xed5af388653567af2f388e6224dc7c4b3241c544"],
    medias: {
      discord: "https://discord.gg/azuki",
      instagram: "https://www.instagram.com/azuki_zen",
    },
  },
  {
    marketCap: 217290837.67265195,
    marketCapChange24h: 0.0018,
    name: "The Sandbox LAND",
    longDesc:
      "The Sandbox is a community-driven platform where creators can monetize voxel assets and gaming experiences on the blockchain. The Sandbox metaverse comprises a map made up of 166,464 LANDS. LAND owners can host contests and events, stake SAND to earn and customize assets, monetize assets and experiences, vote in the metaverse governance, play games that you or others create, and more! Trade the collection and keep your eyes peeled for future drops.",
    slug: "the-sandbox-land",
    link: "https://www.sandbox.game/",
    logo: "https://static.nftgo.io/asset/1624853691744.png",
    blockchain: "ETH",
    contracts: [
      "0x50f5474724e0ee42d9a4e711ccfb275809fd6d4a",
      "0x5cc5b05a8a13e3fbdb0bb9fccd98d38e50f90c38",
    ],
    medias: {
      twitter: "https://www.twitter.com/thesandboxgame",
      discord: "https://discord.gg/vAe4zvY",
      telegram: "https://t.me/sandboxgame",
      medium: "https://www.medium.com/@sandbox-game",
    },
  },
  {
    marketCap: 183303961.15656096,
    marketCapChange24h: 0.0043,
    name: "Doodles",
    longDesc:
      "A community-driven collectibles project featuring art by Burnt Toast. Doodles come in a joyful range of colors, traits and sizes with a collection size of 10,000. Each Doodle allows its owner to vote for experiences and activations paid for by the Doodles Community Treasury.",
    slug: "doodles",
    link: "https://doodles.app/",
    logo: "https://lh3.googleusercontent.com/7B0qai02OdHA8P_EOVK672qUliyjQdQDGNrACxs7WnTgZAkJa_wWURnIFKeOh5VTf8cfTqW3wQpozGedaC9mteKphEOtztls02RlWQ=s130",
    blockchain: "ETH",
    contracts: ["0x8a90cab2b38dba80c64b7734e58ee1db38b8992e"],
    medias: {
      twitter: "https://twitter.com/doodles",
      discord: "http://discord.gg/doodles",
    },
  },
  {
    marketCap: 161142458.99991265,
    marketCapChange24h: 0.0068,
    name: "RTFKT - MNLTH",
    longDesc:
      "Behold a mysterious MNLTH, etched with NIKE & RTFKT markings. It seems to be sentient . . . What does it do? 👁‍🗨",
    slug: "rtfkt---mnlth",
    link: "https://opensea.io/collection/rtfkt-mnlth",
    logo: "https://lh3.googleusercontent.com/gp39NTyxBPazqowYV9XTFxAU4eNk1i7FlmonHW4Zr7eS9UxEvrZ7f04rOLEhDxcuGxsbUx1Rm_N6Ky_Dp4A1ZQYHFAaEWj5YdBF0qg=s120",
    blockchain: "ETH",
    contracts: ["0x86825dfca7a6224cfbd2da48e85df2fc3aa7c4b1"],
    medias: {},
  },
  {
    marketCap: 151589469.11601526,
    marketCapChange24h: -0.0001,
    name: "Cool Cats NFT",
    longDesc:
      "Cool Cats is a collection of 9,999 randomly generated and stylistically curated NFTs that exist on the Ethereum Blockchain. Cool Cat holders can participate in exclusive events such as NFT claims, raffles, community giveaways, and more. Remember, all cats are cool, but some are cooler than others.",
    slug: "cool-cats-nft",
    link: "http://coolcatsnft.com",
    logo: "https://lh3.googleusercontent.com/LIov33kogXOK4XZd2ESj29sqm_Hww5JSdO7AFn5wjt8xgnJJ0UpNV9yITqxra3s_LMEW1AnnrgOVB_hDpjJRA1uF4skI5Sdi_9rULi8=s120",
    blockchain: "ETH",
    contracts: ["0x1a92f7381b9f03921564a437210bb9396471050c"],
    medias: {
      twitter: "https://twitter.com/coolcatsnft",
      discord: "https://discord.gg/X6A4AXrKaR",
      telegram: null,
      instagram: null,
      medium: "https://medium.com/@coolcatsnft",
    },
  },
  {
    marketCap: 131551494.72440745,
    marketCapChange24h: 0.0001,
    name: "Foundation (FND)",
    longDesc:
      "Foundation is building the new creative economy. Create, explore & collect digital art NFTs.",
    slug: "foundation-fnd",
    link: "https://opensea.io/collection/fnd",
    logo: "https://lh3.googleusercontent.com/uUdrzISpIJJVRbm_g6mmu-TUaOERBbPJcNA8KeuwI1HNgXy8Kje3c2XhoMIndnPmyono9NUJE8A2_bTd95iqAcjo9pyy-e47flJy=s120",
    blockchain: "ETH",
    contracts: ["0x3b3ee1931dc30c1957379fac9aba94d1c48a5405"],
    medias: { discord: "https://discord.gg/AQ3VtFh" },
  },
  {
    marketCap: 124477874.77851337,
    marketCapChange24h: -0.0514,
    name: "Bored Ape Chemistry Club",
    longDesc:
      "Bored Ape Chemistry Club consists of 10,000 Mutant Serums, to be airdropped to all Bored Apes. Handle with care. Instructions to follow at 6pm ET 8/28/21.\n",
    slug: "bored-ape-chemistry-club",
    link: "https://opensea.io/collection/bored-ape-chemistry-club",
    logo: "https://lh3.googleusercontent.com/Mf4vImKbzrJUcj7f7RZNOl9iZSEEJgkvpiUp9ugXc9dcpxFe6fvVgxYcRmTI1PnvfL_X1bD3mH4e66j6aJhqLEYm0vvpC8Jy8XJNZOI=s120",
    blockchain: "ETH",
    contracts: ["0x22c36bfdcef207f9c0cc941936eff94d4246d14a"],
    medias: {},
  },
  {
    marketCap: 116331429.77367513,
    marketCapChange24h: 0.0005,
    name: "CyberKongz",
    longDesc:
      "Welcome to an alternate reality, where evolution took a different route and weird apes roam the earth. Some appear normal. Some look weird. And some are just damn cool! Every CyberKong is unique and owns randomized items with different rarities. A few are super rare and even animated!  Maybe some of them look familiar!",
    slug: "cyberkongz",
    link: "https://www.cyberkongz.com/",
    logo: "https://lh3.googleusercontent.com/LIpf9z6Ux8uxn69auBME9FCTXpXqSYFo8ZLO1GaM8T7S3hiKScHaClXe0ZdhTv5br6FE2g5i-J5SobhKFsYfe6CIMCv-UfnrlYFWOM4=s130",
    blockchain: "ETH",
    contracts: ["0x57a204aa1042f6e66dd7730813f4024114d74f37"],
    medias: {
      twitter: "https://twitter.com/CyberKongz",
      discord: "https://discord.com/invite/cyberkongz",
      medium: "https://cyberkongz.medium.com/",
    },
  },
  {
    marketCap: 115229905.89864874,
    marketCapChange24h: 0.021,
    name: "World of Women",
    longDesc:
      "collection of unique, cool and diverse Women, ready to leave a mark in the NFT space! 10,000 randomly generated digital collectibles of various rarity living on the Ethereum blockchain as ERC-721 tokens and hosted on IPFS. Created and Illustrated by Yam Karkai",
    slug: "world-of-women",
    link: "https://worldofwomen.art/",
    logo: "https://lh3.googleusercontent.com/hlXF2pfdF0Lw0Vy78fNs1_E2OLSa6UOiBEv2SZPe2NG4qCrb0ARplv8r7A8o6TLrn0pGi7h4GYREDiCz4f-qlt1lCN8W9FzUFVFYeA=s130",
    blockchain: "ETH",
    contracts: ["0xe785e82358879f061bc3dcac6f0444462d4b5330"],
    medias: {
      twitter: "https://twitter.com/worldofwomennft",
      discord: "https://discord.com/invite/wThn7Qg6pQ",
    },
  },
  {
    marketCap: 105763573.67189819,
    marketCapChange24h: 0.0008,
    name: "Decentraland LAND",
    longDesc:
      "Decentraland is an Ethereum blockchain-powered virtual world, developed and owned by its users, who can create, experience, and monetize content and applications. Join a growing community of virtual world inhabitants who are building the world's largest alternate reality economy on the blockchain.",
    slug: "decentraland-land",
    link: "https://decentraland.org/",
    logo: "https://static.nftgo.io/asset/1626416314237.png",
    blockchain: "ETH",
    contracts: [
      "0xf87e31492faf9a91b02ee0deaad50d51d56d5d4d",
      "0x959e104e1a4db6317fa58f8295f586e1a978c297",
    ],
    medias: {
      twitter: "https://twitter.com/decentraland",
      discord: "https://discord.com/invite/k5ydeZp",
    },
  },
  {
    marketCap: 103985295.77552715,
    marketCapChange24h: 0.0026,
    name: "VeeFriends",
    longDesc:
      "VeeFriends is the name of Gary Vaynerchuk’s NFT collection. He created VeeFriends to bring to life his ambitions of building a community around his creative and business passions using NFT technology and their smart contract capabilities.By owning a VeeFriend NFT, you immediately become part of the VeeFriends community and get access to VeeCon.",
    slug: "veefriends",
    link: "https://veefriends.com/",
    logo: "https://lh3.googleusercontent.com/5y-UCAXiNOFXH551w5bWdZEYOCdHPwbqmcKb-xa3uVQEjQgxvih3HtZWSmzqDqd0uk7kIqFrZhw32Gt6xPBFg4t_n9BKhpou-dwnOg=s0",
    blockchain: "ETH",
    contracts: ["0xa3aee8bce55beea1951ef834b99f3ac60d1abeeb"],
    medias: {
      twitter: "https://twitter.com/veefriends",
      discord: "https://discord.com/invite/veefriends",
      instagram: "https://www.instagram.com/veefriends/",
    },
  },
  {
    marketCap: 103352312.1144595,
    marketCapChange24h: 0,
    name: "CrypToadz by GREMPLIN",
    longDesc:
      "CrypToadz are a collection 6969 small amphibious creatures trying to escape the tyrannical rule of the Evil King Gremplin. Created by Gremplin, with a small bit of help from his friends. This project is in the public domain. Feel free to use the toadz in any way you want.",
    slug: "cryptoadz-by-gremplin",
    link: "https://cryptoadz.io/",
    logo: "https://lh3.googleusercontent.com/iofetZEyiEIGcNyJKpbOafb_efJyeo7QOYnTog8qcQJhqoBU-Vu9l3lXidZhXOAdu6dj4fzWW6BZDU5vLseC-K03rMMu-_j2LvwcbHo=s130",
    blockchain: "ETH",
    contracts: ["0x1cb1a5e65610aeff2551a50f76a87a7d3fb649c6"],
    medias: {
      twitter: "https://twitter.com/cryptoadzNFT",
      discord: "https://discord.com/invite/8QtAYPgjAw",
    },
  },
  {
    marketCap: 101158569.794328,
    marketCapChange24h: 0.0016,
    name: "Bored Ape Kennel Club",
    longDesc:
      "It gets lonely in the swamp sometimes. That's why every ape should have a four-legged companion. To curl up at your feet. To bring you a beer. To fire a missile launcher at that bastard Jimmy the Monkey.\r\n\r\nThat's why we've started the Bored Ape Kennel Club, and why we're offering up a dog NFT for adoption to every single member of the BAYC – for free (you only pay gas).\r\n\r\nAny royalties we accrue on secondary sales will be donated to charity. Learn more at: http://boredapeyachtclub.com/#/kennel-club",
    slug: "bored-ape-kennel-club",
    link: "http://boredapeyachtclub.com/#/kennel-club",
    logo: "https://lh3.googleusercontent.com/l1wZXP2hHFUQ3turU5VQ9PpgVVasyQ79-ChvCgjoU5xKkBA50OGoJqKZeMOR-qLrzqwIfd1HpYmiv23JWm0EZ14owiPYaufqzmj1=s120",
    blockchain: "ETH",
    contracts: ["0xba30e5f9bb24caa003e9f2f0497ad287fdf95623"],
    medias: {
      twitter: "https://twitter.com/boredapeyc",
      discord: "https://discord.gg/wjH7hGz2yS",
      telegram: null,
      instagram: null,
      medium: null,
    },
  },
];

export const nftMarketCap = 18630928815.78179;
