apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ../../secrets/overlays/prod
  - api-prod.yaml
  - canary.yaml
  - grafana-ingress.yaml
  - loki-ingress.yaml

configMapGenerator:
  - name: gas-analysis-env
    literals:
      - ENV="prod"
      - LOG_LEVEL="warn"
      - PGDATABASE="defaultdb"
      - PGHOST=""
      - PGPORT=""
      - PGUSER="default"

patches:
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: 1500m
          memory: 2Gi
    target:
      group: apps
      version: v1
      kind: Deployment
      name: analyze-blocks
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: 1000m
          memory: 1Gi
    target:
      group: apps
      version: v1
      kind: Deployment
      name: analyze-burn-categories
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: 1000m
          memory: 1Gi
    target:
      group: apps
      version: v1
      kind: Deployment
      name: analyze-total-value-secured
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: 500m
          memory: 512Mi
    target:
      group: apps
      version: v1
      kind: Deployment
      name: contract-metadata
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: 500m
          memory: 1Gi
    target:
      group: apps
      version: v1
      kind: Deployment
      name: serve-fees
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: 500m
          memory: 512Mi
    target:
      group: apps
      version: v1
      kind: Deployment
      name: store-eth-price
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: 500m
          memory: 512Mi
    target:
      group: apps
      version: v1
      kind: Deployment
      name: store-market-caps
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: 500m
          memory: 512Mi
    target:
      group: apps
      version: v1
      kind: Deployment
      name: store-pe-ratios
  - patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources/limits
        value:
          cpu: 500m
          memory: 512Mi
    target:
      group: apps
      version: v1
      kind: Deployment
      name: store-validator-rewards
