{
 "title": "Critical Signals",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "serve-fees count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"serve-fees\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "analyze-blocks count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"analyze-blocks\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "time since last crawl profiles success",
   "type": "timeseries",
   "description": "Number of crawl-profiles jobs with status succeeded. The cronjob keeps the last three successes around, meaning we'd see at least three, and at most four if all is running well.",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(time() - kube_cronjob_next_schedule_time{cronjob=\"crawl-profiles\"}) + 3600"
    }
   ]
  },
  {
   "title": "time since last lists sync success",
   "type": "timeseries",
   "description": "Number of sync-lists jobs with status succeeded. The cronjob keeps the last three successes around, meaning we'd see at least three, and at most four if all is running well.",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(time() - kube_cronjob_next_schedule_time{cronjob=\"sync-lists\"}) + 1800"
    }
   ]
  },
  {
   "title": "crawl-followees count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 12 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"crawl-followees\"}"
    }
   ]
  },
  {
   "title": "crawl-followers count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"crawl-followers\"}"
    }
   ]
  },
  {
   "title": "contract-metadata count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"contract-metadata\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "store-eth-price count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 24 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"store-eth-price\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "store-market-caps count",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 24 },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"store-market-caps\"}",
     "legendFormat": "{{deployment}}"
    }
   ]
  }
 ]
}