apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: geth-adam-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"

spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: geth-adam
                port:
                  number: 80
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: geth-adam
# spec:
#   type: LoadBalancer
#   ports:
#     - port: 8546
#       targetPort: 8546
#   selector:
#     app: geth-adam
# ---
apiVersion: v1
kind: Service
metadata:
  name: geth-adam
  labels:
    app: geth-adam
spec:
  ports:
    - port: 8546
      name: ws
    - port: 30303
      name: gethdiscovery
  selector:
    app: geth-adam
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth-adam
spec:
  serviceName: geth-adam
  replicas: 1
  selector:
    matchLabels:
      app: geth-adam
  template:
    metadata:
      labels:
        app: geth-adam
    spec:
      containers:
        - name: geth-adam
          image: ethereum/client-go:v1.10.10
          args: ["--ws", "--ws.addr=0.0.0.0", "--datadir=/data"]
          env:
          ports:
            - containerPort: 8546
              name: ws
            - containerPort: 30303
              name: gethdiscovery
          volumeMounts:
            - name: geth-mainnet-2
              mountPath: "/data"
          resources:
            limits:
              memory: 12000Mi
            requests:
              memory: 10000Mi
              cpu: 4000m
  volumeClaimTemplates:
    - metadata:
        name: geth-mainnet-2
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 800Gi
