{
 "title": "Log Rates",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "alert per hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({level=\"ALERT\"}[1h])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "error per hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({level=\"ERROR\"}[1h])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "warning per hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(count_over_time({level=\"WARNING\"}[1h])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "info per hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(count_over_time({level=\"INFO\"}[1h])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "debug per hour",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(count_over_time({level=\"DEBUG\",app!=\"canary\"}[1h])) by (container)",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}