apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyze-burn-categories
  labels:
    app: analyze-burn-categories
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: analyze-burn-categories
  template:
    metadata:
      labels:
        app: analyze-burn-categories
    spec:
      containers:
        - name: analyze-burn-categories
          image: rg.fr-par.scw.cloud/ultrasoundmoney/gas-analysis
          command: ["node", "src/burn-categories/analyze_burn_categories.js"]
          envFrom:
            - configMapRef:
                name: gas-analysis-env
            - secretRef:
                name: db-password
          env:
            - name: NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
      imagePullSecrets:
        - name: registry-secret
