name: build

on:
  push:
    tags:
      - "staging-*"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: install deps
        run: yarn install
      - name: check types
        run: yarn check-types
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DigitalOcean Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DO_REGISTRY_USERNAME }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.digitalocean.com/gas-analysis/gas-analysis:latest, registry.digitalocean.com/gas-analysis/gas-analysis:${{ github.sha }}
