name: build

on:
  push:
    tags:
      - "staging-*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DigitalOcean Registry
        uses: docker/login-action@v1
        with:
          registry: registry.digitalocean.com/gas-analysis
          username: ${{ secrets.DO_REGISTRY_USERNAME }}
          password: ${{ secrets.DO_REGISTRY_TOKEN }}
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          check-name: test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Provide short sha
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.digitalocean.com/gas-analysis/gas-analysis:latest, registry.digitalocean.com/gas-analysis/gas-analysis:${{ steps.vars.outputs.sha_short }}
