name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Scaleway Registry
        uses: docker/login-action@v2
        with:
          registry: rg.nl-ams.scw.cloud/ultrasoundmoney
          username: ${{ secrets.SCALEWAY_API_KEY }}
          password: ${{ secrets.SCALEWAY_API_KEY }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: rg.nl-ams.scw.cloud/ultrasoundmoney/eth-analysis-ts
          tags: |
            type=sha,prefix=
            type=raw,value=latest
      - name: Wait for tests to succeed
        uses: lewagon/wait-on-check-action@v1.1.1
        with:
          ref: ${{ github.ref }}
          check-name: test
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
      - name: Docker build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
