name: deploy-staging

on:
  push:
    tags:
      - "stag-*"

jobs:
  wait-on-build:
    name: wait on build
    runs-on: ubuntu-latest
    steps:
      - name: Wait for build to succeed
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.ref }}
          check-name: build
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10
  deploy-k8s-resources:
    name: deploy k8s resources
    runs-on: ubuntu-latest
    needs: wait-on-build
    steps:
      - uses: actions/checkout@master
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: apply -f k8s/stag
  deploy-serve-fees:
    name: deploy serve-fees
    runs-on: ubuntu-latest
    needs: deploy-k8s-resources
    steps:
      - uses: actions/checkout@master
      - name: Make short SHA available
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image deployment/serve-fees serve-fees=registry.digitalocean.com/ultrasoundmoney/gas-analysis:${{ steps.vars.outputs.sha_short }}
      - name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: rollout status deployment/serve-fees
  deploy-watch-blocks:
    name: deploy watch-blocks
    runs-on: ubuntu-latest
    needs: deploy-k8s-resources
    steps:
      - uses: actions/checkout@master
      - name: Make short SHA available
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image deployment/watch-blocks watch-blocks=registry.digitalocean.com/ultrasoundmoney/gas-analysis:${{ steps.vars.outputs.sha_short }}
      - name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: rollout status deployment/watch-blocks
  deploy-watch-blocks-dev:
    name: deploy watch-blocks-dev
    runs-on: ubuntu-latest
    needs: deploy-k8s-resources
    steps:
      - uses: actions/checkout@master
      - name: Make short SHA available
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image deployment/watch-blocks-dev watch-blocks-dev=registry.digitalocean.com/ultrasoundmoney/gas-analysis:${{ steps.vars.outputs.sha_short }}
      - name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: rollout status deployment/watch-blocks-dev
  deploy-contract-metadata:
    name: deploy contract-metadata
    runs-on: ubuntu-latest
    needs: deploy-k8s-resources
    steps:
      - uses: actions/checkout@master
      - name: Make short SHA available
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image deployment/contract-metadata contract-metadata=registry.digitalocean.com/ultrasoundmoney/gas-analysis:${{ steps.vars.outputs.sha_short }}
      - name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: rollout status deployment/contract-metadata
  deploy-store-eth-price:
    name: deploy store-eth-price
    runs-on: ubuntu-latest
    needs: deploy-k8s-resources
    steps:
      - uses: actions/checkout@master
      - name: Make short SHA available
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image deployment/store-eth-price store-eth-price=registry.digitalocean.com/ultrasoundmoney/gas-analysis:${{ steps.vars.outputs.sha_short }}
      - name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: rollout status deployment/store-eth-price
  deploy-store-market-caps:
    name: deploy store-market-caps
    runs-on: ubuntu-latest
    needs: deploy-k8s-resources
    steps:
      - uses: actions/checkout@master
      - name: Make short SHA available
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image deployment/store-market-caps store-market-caps=registry.digitalocean.com/ultrasoundmoney/gas-analysis:${{ steps.vars.outputs.sha_short }}
      - name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: rollout status deployment/store-market-caps
  deploy-store-eth-price-dev:
    name: deploy store-eth-price-dev
    runs-on: ubuntu-latest
    needs: deploy-k8s-resources
    steps:
      - uses: actions/checkout@master
      - name: Make short SHA available
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image deployment/store-eth-price-dev store-eth-price-dev=registry.digitalocean.com/ultrasoundmoney/gas-analysis:${{ steps.vars.outputs.sha_short }}
      - name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: rollout status deployment/store-eth-price-dev
  deploy-store-market-caps-dev:
    name: deploy store-market-caps-dev
    runs-on: ubuntu-latest
    needs: deploy-k8s-resources
    steps:
      - uses: actions/checkout@master
      - name: Make short SHA available
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: deploy
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image deployment/store-market-caps-dev store-market-caps-dev=registry.digitalocean.com/ultrasoundmoney/gas-analysis:${{ steps.vars.outputs.sha_short }}
      - name: Verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: rollout status deployment/store-market-caps-dev
