name: merge tagged commit to prod
on:
  push:
    tags:
      - "prod-*"
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: merge to prod
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: main
          target_branch: prod
          github_token: ${{ github.token }}
