name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - name: yarn install, build and test
        run: |
          yarn --skip-integrity-check
          yarn check
          yarn lint
          yarn test
