name: test

on:
  push:
    branches:
      - main
      - "hotfix/*"
  push:
    pull_requests:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: install deps
        run: yarn install
      - name: check types
        run: yarn check-types
      - name: lint
        run: yarn lint
      - name: test
        run: yarn test
